### ISSUE TITLE
Not an issue, just a Compliment

### ISSUE THREAD

**Issue by elementWebDev** [MasterTemple/ScriptureHub#1]
I have been searching off / on for over 2 weeks for an API I could use for a simple app / widget and stumbled across this repo. Awesome work so far!

About me... I have been taking online courses since around 2014 and am now working on Node and just getting into MongoDB. I have been wanting to build / incorporate something useful and want to do something for the Gospel :)

Anyway, I just wanted to say I saw your work and it's appreciated 🥇

**Comment by MasterTemple** [comment]
Hello,

What were you searching for? I did not expect anyone to find this. Sorry, I never updated the readme cause I didn’t think anyone would be looking at the project, but I might do that tomorrow.

If you want to preview this site, you can go [here](https://htmlpreview.github.io/?https://raw.githubusercontent.com/MasterTemple/ScriptureHub/main/index.html). I think the program works for the most part, however I am aware that the most prophets and poetry books do not work (at least for the verses, the interlinear and commentaries still should work).

I'm hardly an adult and only have about a year of experience with programming.

**Comment by elementWebDev** [comment]
I have learned a bit just seeing your approach and syntax, I understand it, just haven't seen someone else work through it so well. I may only be using part of this to implement into something later, but I appreciate your work!

**Comment by MasterTemple** [comment]
I have no formal experience. I would not recommend copying my project structure or whatever because it is likely below standard.
